(function(){
'use strict';
const S={data:[],headers:[],map:{item:'',dept:'',qty:'',value:'',mins:''},name:''};
const A={ar:{nav:'استيراد البيانات',title:'مركز استيراد البيانات',sub:'استورد ملفًا، راجع المعاينة، طابق الأعمدة، ثم ابدأ التحليل.',drop:'اسحب ملف CSV أو Excel أو JSON هنا',pick:'أو اختر ملفًا من جهازك',paste:'لصق جدول',read:'قراءة البيانات',template:'تحميل نموذج CSV',preview:'معاينة البيانات',mapping:'مطابقة الأعمدة',item:'العنصر',dept:'القسم',qty:'الكمية',value:'القيمة',mins:'الوقت بالدقائق',ignore:'تجاهل',replace:'استبدال البيانات الحالية',append:'إضافة إلى البيانات الحالية',import:'استيراد إلى المنصة',analyze:'استيراد وبدء التحليل',clear:'مسح',empty:'لم يتم تحميل بيانات بعد.',ready:'البيانات جاهزة',invalid:'تعذر قراءة الملف. تحقق من التنسيق.',need:'حدد أعمدة العنصر والقسم والقيمة على الأقل.',done:'تم استيراد البيانات بنجاح',rows:'صف',cols:'عمود'},en:{nav:'Import Data',title:'Data Import Center',sub:'Import a file, preview it, map columns, then start analysis.',drop:'Drop a CSV, Excel, or JSON file here',pick:'or choose a file from your device',paste:'Paste Table',read:'Read Data',template:'Download CSV Template',preview:'Data Preview',mapping:'Column Mapping',item:'Item',dept:'Department',qty:'Quantity',value:'Value',mins:'Time in minutes',ignore:'Ignore',replace:'Replace current data',append:'Append to current data',import:'Import to Platform',analyze:'Import & Start Analysis',clear:'Clear',empty:'No data loaded yet.',ready:'Data is ready',invalid:'Could not read the file. Check the format.',need:'Map at least Item, Department, and Value.',done:'Data imported successfully',rows:'rows',cols:'columns'}};
function T(k){return A[(typeof lang!=='undefined'&&lang==='en')?'en':'ar'][k]}
function E(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function N(s){return String(s??'').toLowerCase().replace(/[\s_\-\/\\]+/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه')}
function note(m){let x=document.getElementById('bsImportToast');if(!x){x=document.createElement('div');x.id='bsImportToast';x.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:12000;background:#111725;color:#fff;border:1px solid #3a445b;padding:11px 16px;border-radius:13px;box-shadow:0 14px 35px #0009;font:700 13px Cairo,Arial';document.body.appendChild(x)}x.textContent=m;x.hidden=false;clearTimeout(x._t);x._t=setTimeout(()=>x.hidden=true,2500)}
function styles(){let s=document.createElement('style');s.textContent=`#importPage .ig{display:grid;grid-template-columns:1fr 1fr;gap:14px}.iz{border:1.5px dashed #59627a;border-radius:18px;padding:30px 18px;text-align:center;background:#0d1019;cursor:pointer}.iz.drag{border-color:var(--gold);box-shadow:0 0 0 4px rgba(231,193,95,.08)}.iz b{display:block;color:var(--gold);margin:8px}.itabs{display:flex;gap:8px;margin-bottom:12px}.itab{border:1px solid #343b50;background:#111521;color:#fff;border-radius:11px;padding:9px 13px;font-weight:800;cursor:pointer}.itab.active{border-color:var(--gold);color:var(--gold)}.ipan{display:none}.ipan.active{display:block}.ipaste{width:100%;min-height:145px;padding:12px;border-radius:13px;border:1px solid #34394d;background:#090b12;color:#fff}.imap{display:grid;grid-template-columns:repeat(5,minmax(110px,1fr));gap:9px}.imap label{display:block;color:var(--gold);font-size:.76rem;font-weight:800;margin-bottom:5px}.imap select{width:100%;padding:10px;border-radius:11px;border:1px solid #34394d;background:#090b12;color:#fff}.iact,.imode,.imeta{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.ipill{padding:7px 10px;border-radius:999px;background:#111725;border:1px solid #30394e;font-size:.76rem}.iprev{overflow:auto;max-height:330px;border:1px solid var(--line);border-radius:14px}.iprev table{min-width:700px}.iprev th{position:sticky;top:0}.iempty{text-align:center;color:var(--muted);padding:32px}@media(max-width:850px){#importPage .ig{grid-template-columns:1fr}.imap{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.imap{grid-template-columns:1fr}.iact .btn{width:100%}}`;document.head.appendChild(s)}
function ui(){if(document.getElementById('importPage'))return;styles();let aside=document.querySelector('aside'),set=aside&&aside.querySelector('[data-page="settingsPage"]');if(aside){let b=document.createElement('button');b.className='nav-btn';b.dataset.page='importPage';b.innerHTML='<span class="nav-icon">📥</span><span>'+T('nav')+'</span>';aside.insertBefore(b,set);b.onclick=()=>openPage('importPage')}
let home=document.querySelector('.home-grid');if(home){let c=document.createElement('article');c.className='card action-card';c.innerHTML='<div class="big-icon">📥</div><h3>'+T('nav')+'</h3><p>CSV • Excel • JSON • Paste</p><span class="arrow">←</span>';c.onclick=()=>openPage('importPage');home.appendChild(c)}
let p=document.createElement('section');p.className='page';p.id='importPage';p.innerHTML=`<div class="page-head"><div><h2>${T('title')}</h2><p>${T('sub')}</p></div><button class="btn dark" id="iClear">${T('clear')}</button></div><div class="ig"><div class="card"><div class="itabs"><button class="itab active" data-tab="file">📄 CSV / Excel / JSON</button><button class="itab" data-tab="paste">📋 ${T('paste')}</button></div><div class="ipan active" data-pan="file"><div class="iz" id="iDrop"><div style="font-size:2.3rem">📥</div><b>${T('drop')}</b><span>${T('pick')}</span><input id="iFile" type="file" accept=".csv,.xlsx,.xls,.json" hidden></div><div class="iact"><button class="btn dark" id="iTemplate">⬇ ${T('template')}</button></div></div><div class="ipan" data-pan="paste"><textarea class="ipaste" id="iPaste" placeholder="${T('paste')}..."></textarea><div class="iact"><button class="btn" id="iRead">${T('read')}</button></div></div><div id="iStatus" class="notice" style="margin-top:12px">${T('empty')}</div></div><div class="card"><h3>${T('mapping')}</h3><div class="imap" id="iMap"></div><div class="imode"><label><input type="radio" name="iMode" value="replace" checked> ${T('replace')}</label><label><input type="radio" name="iMode" value="append"> ${T('append')}</label></div><div class="iact"><button class="btn green" id="iImport">${T('import')}</button><button class="btn" id="iAnalyze">🚀 ${T('analyze')}</button></div></div></div><div class="card" style="margin-top:14px"><h3>${T('preview')}</h3><div class="imeta" id="iMeta"></div><div class="iprev" id="iPreview"><div class="iempty">${T('empty')}</div></div></div>`;document.querySelector('main').appendChild(p);wire();mapUI()}
function wire(){document.querySelectorAll('.itab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.itab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.ipan').forEach(x=>x.classList.toggle('active',x.dataset.pan===b.dataset.tab))});let d=document.getElementById('iDrop'),f=document.getElementById('iFile');d.onclick=()=>f.click();f.onchange=e=>e.target.files[0]&&file(e.target.files[0]);['dragenter','dragover'].forEach(v=>d.addEventListener(v,e=>{e.preventDefault();d.classList.add('drag')}));['dragleave','drop'].forEach(v=>d.addEventListener(v,e=>{e.preventDefault();d.classList.remove('drag')}));d.addEventListener('drop',e=>e.dataTransfer.files[0]&&file(e.dataTransfer.files[0]));document.getElementById('iRead').onclick=()=>set(parseCSV(document.getElementById('iPaste').value,document.getElementById('iPaste').value.includes('\t')?'\t':null),'Pasted Data');document.getElementById('iTemplate').onclick=template;document.getElementById('iClear').onclick=clearAll;document.getElementById('iImport').onclick=()=>commit(false);document.getElementById('iAnalyze').onclick=()=>commit(true)}
function parseCSV(text,del){let d=del||((text.split(/\r?\n/)[0].match(/\t/g)||[]).length>(text.split(/\r?\n/)[0].match(/,/g)||[]).length?'\t':','),a=[],r=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){v+='"';i++}else q=!q}else if(c===d&&!q){r.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;r.push(v);v='';if(r.some(x=>String(x).trim()))a.push(r);r=[]}else v+=c}r.push(v);if(r.some(x=>String(x).trim()))a.push(r);if(!a.length)return[];let h=a[0].map((x,i)=>String(x||('Column '+(i+1))).trim());return a.slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])))}
async function file(x){try{let e=x.name.split('.').pop().toLowerCase(),data;if(e==='csv')data=parseCSV(await x.text());else if(e==='json'){let j=JSON.parse(await x.text());data=Array.isArray(j)?j:(j.rows||[])}else{await xlsx();let w=XLSX.read(await x.arrayBuffer(),{type:'array'}),s=w.Sheets[w.SheetNames[0]];data=XLSX.utils.sheet_to_json(s,{defval:''})}set(data,x.name)}catch(e){console.error(e);document.getElementById('iStatus').textContent=T('invalid');note(T('invalid'))}}
function xlsx(){if(window.XLSX)return Promise.resolve();return new Promise((r,j)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=r;s.onerror=j;document.head.appendChild(s)})}
function set(data,name){S.data=Array.isArray(data)?data:[];S.headers=S.data[0]?Object.keys(S.data[0]):[];S.name=name;guess();mapUI();preview();document.getElementById('iStatus').textContent=S.data.length?`${T('ready')}: ${S.data.length} ${T('rows')}`:T('empty')}
function guess(){let syn={item:['item','product','name','العنصر','المنتج','الصنف','الطبق','الخدمه'],dept:['department','dept','section','category','القسم','الفئه'],qty:['quantity','qty','count','units','الكميه','العدد'],value:['value','revenue','sales','amount','price','total','القيمه','الايراد','المبيعات','السعر'],mins:['minutes','mins','duration','time','الوقت','الدقائق','المده']};Object.keys(syn).forEach(k=>S.map[k]=S.headers.find(h=>syn[k].some(x=>N(h)===N(x)||N(h).includes(N(x))))||'')}
function mapUI(){let g=document.getElementById('iMap');if(!g)return;g.innerHTML=['item','dept','qty','value','mins'].map(k=>`<div><label>${T(k)}</label><select data-k="${k}"><option value="">— ${T('ignore')} —</option>${S.headers.map(h=>`<option value="${E(h)}" ${S.map[k]===h?'selected':''}>${E(h)}</option>`).join('')}</select></div>`).join('');g.querySelectorAll('select').forEach(x=>x.onchange=()=>S.map[x.dataset.k]=x.value)}
function preview(){let w=document.getElementById('iPreview'),m=document.getElementById('iMeta');if(!S.data.length){w.innerHTML=`<div class="iempty">${T('empty')}</div>`;m.innerHTML='';return}m.innerHTML=`<span class="ipill">📄 ${E(S.name)}</span><span class="ipill">${S.data.length} ${T('rows')}</span><span class="ipill">${S.headers.length} ${T('cols')}</span>`;w.innerHTML=`<table><thead><tr>${S.headers.map(h=>`<th>${E(h)}</th>`).join('')}</tr></thead><tbody>${S.data.slice(0,8).map(r=>`<tr>${S.headers.map(h=>`<td>${E(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function num(v){return Number(String(v??'').replace(/[^0-9.\-]/g,''))||0}
function commit(analyze){document.querySelectorAll('#iMap select').forEach(x=>S.map[x.dataset.k]=x.value);if(!S.data.length)return note(T('empty'));if(!S.map.item||!S.map.dept||!S.map.value)return note(T('need'));let z=S.data.map((r,i)=>({item:String(r[S.map.item]??('Item '+(i+1))),dept:String(r[S.map.dept]??'General'),qty:S.map.qty?num(r[S.map.qty]):1,value:num(r[S.map.value]),mins:S.map.mins?Math.max(1,num(r[S.map.mins])):1}));let mode=document.querySelector('input[name="iMode"]:checked').value;if(mode==='replace')rows.splice(0,rows.length,...z);else rows.push(...z);renderRows();updateMetrics();localStorage.setItem('bs_bi_rows',JSON.stringify(rows));note(`${T('done')}: ${z.length}`);openPage(analyze?'analysisPage':'dataPage')}
function template(){let b=new Blob(['\ufeffItem,Department,Quantity,Value,Minutes\nProduct A,Sales,10,500,60\nProduct B,Marketing,8,420,45'],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='bs-import-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function clearAll(){S.data=[];S.headers=[];S.map={item:'',dept:'',qty:'',value:'',mins:''};document.getElementById('iPaste').value='';mapUI();preview();document.getElementById('iStatus').textContent=T('empty')}
window.addEventListener('DOMContentLoaded',ui);
})();